name: drink_shop_flutter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  awesome_snackbar_content: ^0.1.3
  cloud_firestore: ^4.9.2
  convex_bottom_bar: ^3.2.0
  dropdown_button2: ^2.3.9
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  flutter_spinkit: ^5.2.0
  flutter_staggered_animations: ^1.1.1
  flutter_typeahead: ^5.0.1
  form_builder_validators: ^9.1.0
  get: ^4.6.6
  intl: ^0.18.1
  sliver_app_bar_builder: ^1.1.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
